apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  nginx.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://frontend-clusterip:80;
        }
    }

    server {
        listen 4000;
        location / {
            proxy_pass http://demo-server-clusterip:4000;
        }
    }

  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid

  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'demo-server'
        static_configs:
          - targets: ['demo-server-clusterip:4000']
        metrics_path: /metrics
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-server-config
data:
  NODE_ENV: "production"
  CLIENT_URL: "http://frontend-clusterip:2000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DISABLE_REDIS_QUEUES: "false"
  PENDING_ORDER_WORKER_CONCURRENCY: "5"
  EMAIL_WORKER_CONCURRENCY: "10"
  RATE_LIMIT_REQUESTS: "100"
  LOKI_URL: "http://grafana-loki-clusterip:3100"
